yml added stop server

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -21,6 +21,9 @@ jobs:
       run: npx run start 
     - name: Run Playwright tests
       run: npx playwright test
+    - name: Stop server
+        if: always() # Ensures this step runs even if tests fail
+        run: kill $(lsof -t -i:4200) || true
     - uses: actions/upload-artifact@v4
       if: ${{ !cancelled() }}
       with:
